<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds for all actual and existing regions, provinces, and municipalities in Mindanao.
     */
    public function run(): void
    {
        $destinations = [
            // ==========================================
            // REGION IX - ZAMBOANGA PENINSULA
            // ==========================================
            // Zamboanga del Norte
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Dipolog City', 'destination_rate' => 3500.00, 'description' => 'Provincial capital & Bottled Sardines Capital.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Dapitan City', 'destination_rate' => 3600.00, 'description' => 'Historic Shrine City of the South.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Bacungan (Leon T. Postigo)', 'destination_rate' => 4000.00, 'description' => 'Coastal municipality in Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Baliguian', 'destination_rate' => 4200.00, 'description' => 'Southern coastal town in Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Godod', 'destination_rate' => 4100.00, 'description' => 'Inland municipality in Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Gutalac', 'destination_rate' => 4300.00, 'description' => 'Agricultural coastal town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Jose Dalman', 'destination_rate' => 3700.00, 'description' => 'Coastal municipality in northern Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Kalawit', 'destination_rate' => 4200.00, 'description' => 'Inland town bordering Zamboanga Sibugay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Katipunan', 'destination_rate' => 3600.00, 'description' => 'Municipality adjacent to Dipolog City.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'La Libertad', 'destination_rate' => 3800.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Labason', 'destination_rate' => 4100.00, 'description' => 'Major trade town in western Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Liloy', 'destination_rate' => 4000.00, 'description' => 'Commercial hub in western Zamboanga Peninsula.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Manukan', 'destination_rate' => 3700.00, 'description' => 'Coastal agricultural town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Mutia', 'destination_rate' => 3800.00, 'description' => 'Highland town near Mt. Malindang.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Piñan', 'destination_rate' => 3600.00, 'description' => 'Agricultural hub near Dapitan.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Polanco', 'destination_rate' => 3500.00, 'description' => 'Neighboring municipality of Dipolog.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'President Manuel A. Roxas', 'destination_rate' => 3600.00, 'description' => 'Coastal town in Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Salug', 'destination_rate' => 4100.00, 'description' => 'Agricultural coastal town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Sergio Osmeña Sr.', 'destination_rate' => 3900.00, 'description' => 'Highland vegetable basin town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Siayan', 'destination_rate' => 4000.00, 'description' => 'Inland mountain municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Sibuco', 'destination_rate' => 4500.00, 'description' => 'Southernmost town bordering Zamboanga City.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Sibutad', 'destination_rate' => 3700.00, 'description' => 'Northernmost coastal town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Sindangan', 'destination_rate' => 3800.00, 'description' => 'Major commercial hub of northern Zamboanga.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Siocon', 'destination_rate' => 4400.00, 'description' => 'Mining and agricultural coastal town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Sirawai', 'destination_rate' => 4500.00, 'description' => 'Coastal municipality in southwestern Zamboanga peninsula.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Norte', 'city' => 'Tampilisan', 'destination_rate' => 4100.00, 'description' => 'Inland rubber and coconut producing town.'],

            // Zamboanga del Sur
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Pagadian City', 'destination_rate' => 3200.00, 'description' => 'Provincial capital & Regional administrative center.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Zamboanga City', 'destination_rate' => 4000.00, 'description' => 'Highly Urbanized City, Asia’s Latin City.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Aurora', 'destination_rate' => 3000.00, 'description' => 'Gateway town connecting Zamboanga del Sur and Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Bayog', 'destination_rate' => 3500.00, 'description' => 'Mining and agricultural inland town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Dimataling', 'destination_rate' => 3600.00, 'description' => 'Coastal town on Dumanquilas Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Dinas', 'destination_rate' => 3500.00, 'description' => 'Coastal municipality on Illana Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Dumalinao', 'destination_rate' => 3300.00, 'description' => 'Neighboring municipality of Pagadian City.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Dumingag', 'destination_rate' => 3500.00, 'description' => 'Organic agriculture capital of Zamboanga del Sur.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Guipos', 'destination_rate' => 3400.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Josefina', 'destination_rate' => 3600.00, 'description' => 'Inland municipality at the border of Zamboanga del Norte.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Kumalarang', 'destination_rate' => 3600.00, 'description' => 'Coastal town on Dumanquilas Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Labangan', 'destination_rate' => 3300.00, 'description' => 'Rice granary town adjacent to Pagadian.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Lapuyan', 'destination_rate' => 3600.00, 'description' => 'Subanen cultural heartland town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Mahayag', 'destination_rate' => 3400.00, 'description' => 'Agricultural hub of Salug Valley.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Margosatubig', 'destination_rate' => 3700.00, 'description' => 'Historic port town on Dumanquilas Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Midsalip', 'destination_rate' => 3600.00, 'description' => 'Highland agricultural town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Molave', 'destination_rate' => 3400.00, 'description' => 'Commercial trade center in Salug Valley.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Pitogo', 'destination_rate' => 3700.00, 'description' => 'Peninsular coastal town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Ramon Magsaysay', 'destination_rate' => 3400.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'San Pablo', 'destination_rate' => 3500.00, 'description' => 'Coastal town on Illana Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'San Miguel', 'destination_rate' => 3500.00, 'description' => 'Agricultural interior town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Sominot', 'destination_rate' => 3500.00, 'description' => 'Highland interior municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Tabina', 'destination_rate' => 3800.00, 'description' => 'Southern tip peninsula town of Zamboanga del Sur.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Tambulig', 'destination_rate' => 3400.00, 'description' => 'Rice producing town bordering Misamis Occidental.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Tigbao', 'destination_rate' => 3400.00, 'description' => 'Interior agricultural municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Tukuran', 'destination_rate' => 3400.00, 'description' => 'Coastal town on Illana Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga del Sur', 'city' => 'Vincenzo A. Sagun', 'destination_rate' => 3800.00, 'description' => 'Fishing municipality on Dumanquilas Bay.'],

            // Zamboanga Sibugay
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Ipil', 'destination_rate' => 3500.00, 'description' => 'Provincial capital of Zamboanga Sibugay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Alicia', 'destination_rate' => 3800.00, 'description' => 'Coastal municipality on Dumanquilas Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Buug', 'destination_rate' => 3600.00, 'description' => 'Commercial junction town in Zamboanga Sibugay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Diplahan', 'destination_rate' => 3700.00, 'description' => 'Coal mining municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Imelda', 'destination_rate' => 3700.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Kabasalan', 'destination_rate' => 3600.00, 'description' => 'Rubber production capital of Sibugay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Mabuhay', 'destination_rate' => 4200.00, 'description' => 'Olutanga Island municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Malangas', 'destination_rate' => 3800.00, 'description' => 'Historical coal mining port town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Naga', 'destination_rate' => 3700.00, 'description' => 'Coastal town on Sibuguey Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Olutanga', 'destination_rate' => 4300.00, 'description' => 'Island municipality on Olutanga Island.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Payao', 'destination_rate' => 3900.00, 'description' => 'Coastal fishing municipality.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Roseller Lim', 'destination_rate' => 3700.00, 'description' => 'Coastal rubber producing town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Siay', 'destination_rate' => 3600.00, 'description' => 'Agricultural municipality on Sibuguey Bay.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Talusan', 'destination_rate' => 4200.00, 'description' => 'Island town on Olutanga Island.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Titay', 'destination_rate' => 3700.00, 'description' => 'Major highway junction & agricultural town.'],
            ['region' => 'Region IX (Zamboanga Peninsula)', 'province' => 'Zamboanga Sibugay', 'city' => 'Tungawan', 'destination_rate' => 3800.00, 'description' => 'Southernmost town bordering Zamboanga City.'],

            // ==========================================
            // REGION X - NORTHERN MINDANAO
            // ==========================================
            // Bukidnon
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Malaybalay City', 'destination_rate' => 1800.00, 'description' => 'Provincial capital of Bukidnon.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Valencia City', 'destination_rate' => 2000.00, 'description' => 'Commercial center of Bukidnon.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Baungon', 'destination_rate' => 1600.00, 'description' => 'Border town near Cagayan de Oro.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Cabanglasan', 'destination_rate' => 2200.00, 'description' => 'Eastern agricultural municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Damulog', 'destination_rate' => 2600.00, 'description' => 'Southernmost town bordering Cotabato.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Dangcagan', 'destination_rate' => 2400.00, 'description' => 'Southern inland town in Bukidnon.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Don Carlos', 'destination_rate' => 2300.00, 'description' => 'Agricultural and trade hub.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Impasugong', 'destination_rate' => 1900.00, 'description' => 'Home of Tribal Eco-Tourism & Communal Ranch.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Kadingilan', 'destination_rate' => 2500.00, 'description' => 'Southwestern agricultural municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Kibawe', 'destination_rate' => 2500.00, 'description' => 'Southern agricultural town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Kitaotao', 'destination_rate' => 2400.00, 'description' => 'Mountainous agricultural town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Lantapan', 'destination_rate' => 2000.00, 'description' => 'Highland vegetable basket at Mt. Kitanglad.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Libona', 'destination_rate' => 1500.00, 'description' => 'Pineapple growing town near CDO.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Malitbog', 'destination_rate' => 1800.00, 'description' => 'Northern mountain town bordering Misamis Oriental.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Manolo Fortich', 'destination_rate' => 1500.00, 'description' => 'Dahilayan Adventure Park & Del Monte plantation.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Maramag', 'destination_rate' => 2200.00, 'description' => 'Agricultural & educational center of Bukidnon.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Pangantucan', 'destination_rate' => 2400.00, 'description' => 'Gateway to Mt. Kalatungan.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Quezon', 'destination_rate' => 2400.00, 'description' => 'Blue Water Cave & Pulangi River area.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'San Fernando', 'destination_rate' => 2500.00, 'description' => 'Eco-tourism and forestry municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Sumilao', 'destination_rate' => 1700.00, 'description' => 'Alalum Falls and farm eco-tourism.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Bukidnon', 'city' => 'Talakag', 'destination_rate' => 1700.00, 'description' => 'Highland agricultural basin town.'],

            // Camiguin
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Camiguin', 'city' => 'Mambajao', 'destination_rate' => 3500.00, 'description' => 'Capital town of Camiguin Island.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Camiguin', 'city' => 'Catarman', 'destination_rate' => 3800.00, 'description' => 'Sunken Cemetery & Gui-ob Church Ruins.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Camiguin', 'city' => 'Guinsiliban', 'destination_rate' => 3700.00, 'description' => 'Southernmost entry town of Camiguin.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Camiguin', 'city' => 'Mahinog', 'destination_rate' => 3600.00, 'description' => 'Mantigue Island entry point.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Camiguin', 'city' => 'Sagay', 'destination_rate' => 3700.00, 'description' => 'Coastal town with springs and waterfalls.'],

            // Lanao del Norte
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Iligan City', 'destination_rate' => 2000.00, 'description' => 'Highly Urbanized City, City of Majestic Waterfalls.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Tubod', 'destination_rate' => 2500.00, 'description' => 'Provincial capital of Lanao del Norte.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Bacolod', 'destination_rate' => 2300.00, 'description' => 'Coastal municipality in Lanao del Norte.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Baloi', 'destination_rate' => 2100.00, 'description' => 'Municipality hosting Agus II Hydroelectric power.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Baroy', 'destination_rate' => 2500.00, 'description' => 'Coastal town neighboring capital Tubod.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Kapatagan', 'destination_rate' => 2600.00, 'description' => 'Commercial & agricultural hub of western Lanao.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Kauswagan', 'destination_rate' => 2200.00, 'description' => 'Coastal organic farming town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Kolambugan', 'destination_rate' => 2400.00, 'description' => 'Ferry port municipality facing Ozamiz City.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Lala', 'destination_rate' => 2500.00, 'description' => 'Crab capital of Lanao del Norte.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Linamon', 'destination_rate' => 2100.00, 'description' => 'Beach resort town next to Iligan City.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Magsaysay', 'destination_rate' => 2600.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Maigo', 'destination_rate' => 2300.00, 'description' => 'Coastal town between Bacolod and Kolambugan.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Matungao', 'destination_rate' => 2300.00, 'description' => 'Inland municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Munai', 'destination_rate' => 2500.00, 'description' => 'Inland mountain municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Nunungan', 'destination_rate' => 2800.00, 'description' => 'Highland interior town with Mt. Nunungan lake.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Pantao Ragat', 'destination_rate' => 2400.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Pantar', 'destination_rate' => 2200.00, 'description' => 'Gateway town to Lanao del Sur.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Poona Piagapo', 'destination_rate' => 2400.00, 'description' => 'Inland municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Salvador', 'destination_rate' => 2600.00, 'description' => 'Agricultural interior municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Sapad', 'destination_rate' => 2600.00, 'description' => 'Agricultural municipality in western Lanao.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Sultan Naga Dimaporo', 'destination_rate' => 2800.00, 'description' => 'Coastal town on Illana Bay.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Tagoloan', 'destination_rate' => 2300.00, 'description' => 'Inland municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Lanao del Norte', 'city' => 'Tangcal', 'destination_rate' => 2500.00, 'description' => 'Interior mountain municipality.'],

            // Misamis Occidental
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Oroquieta City', 'destination_rate' => 2600.00, 'description' => 'Provincial capital of Misamis Occidental.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Ozamiz City', 'destination_rate' => 2800.00, 'description' => 'Major port & Cotta Shrine pilgrimage destination.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Tangub City', 'destination_rate' => 2900.00, 'description' => 'Christmas Symbols Capital of Mindanao.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Aloran', 'destination_rate' => 2700.00, 'description' => 'Coastal town between Oroquieta and Panaon.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Baliangao', 'destination_rate' => 3100.00, 'description' => 'Northernmost town with marine sanctuary beaches.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Bonifacio', 'destination_rate' => 2900.00, 'description' => 'Southern agricultural municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Calamba', 'destination_rate' => 2800.00, 'description' => 'Inland commercial hub.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Clarin', 'destination_rate' => 2800.00, 'description' => 'Agricultural town famous for house of suman.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Concepcion', 'destination_rate' => 3000.00, 'description' => 'Highland mountain municipality in Mt. Malindang.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Don Victoriano Chiongbian', 'destination_rate' => 3200.00, 'description' => 'Highland summer capital of Misamis Occidental.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Jimenez', 'destination_rate' => 2700.00, 'description' => 'Heritage town with historic Spanish-era church.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Lopez Jaena', 'destination_rate' => 2700.00, 'description' => 'Coastal municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Panaon', 'destination_rate' => 2700.00, 'description' => 'Coastal agricultural town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Plaridel', 'destination_rate' => 2800.00, 'description' => 'Major coconut producing coastal municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Sapang Dalaga', 'destination_rate' => 2900.00, 'description' => 'Bawa Falls & Caluya Shrine eco-destination.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Sinacaban', 'destination_rate' => 2800.00, 'description' => 'Coastal town on Murcielagos Bay.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Occidental', 'city' => 'Tudela', 'destination_rate' => 2800.00, 'description' => 'Agricultural coastal town.'],

            // Misamis Oriental
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Cagayan de Oro City', 'destination_rate' => 1200.00, 'description' => 'Highly Urbanized City, Regional Center & White Water Rafting Capital.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'El Salvador City', 'destination_rate' => 1400.00, 'description' => 'Divine Mercy Shrine pilgrimage destination.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Gingoog City', 'destination_rate' => 1800.00, 'description' => 'City of Waterfalls.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Alubijid', 'destination_rate' => 1400.00, 'description' => 'Educational & coastal municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Balingasag', 'destination_rate' => 1600.00, 'description' => 'Major commercial center of eastern Misamis Oriental.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Balingoan', 'destination_rate' => 1800.00, 'description' => 'Port municipality to Camiguin Island.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Binuangan', 'destination_rate' => 1700.00, 'description' => 'Coastal town with Our Lady of Lourdes Shrine.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Claveria', 'destination_rate' => 1500.00, 'description' => 'Highland vegetable basin & Flight 387 Shrine.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Gitagum', 'destination_rate' => 1400.00, 'description' => 'Coastal town west of CDO.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Initao', 'destination_rate' => 1500.00, 'description' => 'Initao-Libertad Protected Seascape & Beach.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Jasaan', 'destination_rate' => 1500.00, 'description' => 'Spring resort municipality.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Kinoguitan', 'destination_rate' => 1800.00, 'description' => 'Coastal municipality in eastern Misamis Oriental.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Lagonglong', 'destination_rate' => 1600.00, 'description' => 'Coastal agricultural town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Laguindingan', 'destination_rate' => 1300.00, 'description' => 'Home of Laguindingan International Airport.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Libertad', 'destination_rate' => 1500.00, 'description' => 'Coastal municipality with marine sanctuaries.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Lugait', 'destination_rate' => 1700.00, 'description' => 'Industrial cement manufacturing town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Magsaysay', 'destination_rate' => 1900.00, 'description' => 'Easternmost town bordering Agusan del Norte.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Manticao', 'destination_rate' => 1600.00, 'description' => 'Agricultural and coastal town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Medina', 'destination_rate' => 1800.00, 'description' => 'Duka Bay diving and beach resort area.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Naawan', 'destination_rate' => 1500.00, 'description' => 'Coastal town with university marine research site.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Opol', 'destination_rate' => 1300.00, 'description' => 'Popular beach destination next to Cagayan de Oro.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Salay', 'destination_rate' => 1700.00, 'description' => 'Handmade paper craft & coastal town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Sugbongcogon', 'destination_rate' => 1800.00, 'description' => 'Coastal municipality in eastern coast.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Tagoloan', 'destination_rate' => 1400.00, 'description' => 'PHIVIDEC Industrial Estate hub.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Talisayan', 'destination_rate' => 1800.00, 'description' => 'Coastal eco-tourism town.'],
            ['region' => 'Region X (Northern Mindanao)', 'province' => 'Misamis Oriental', 'city' => 'Villanueva', 'destination_rate' => 1400.00, 'description' => 'Industrial hub adjacent to Tagoloan.'],

            // ==========================================
            // REGION XI - DAVAO REGION
            // ==========================================
            // Davao de Oro
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Nabunturan', 'destination_rate' => 2500.00, 'description' => 'Provincial capital of Davao de Oro.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Compostela', 'destination_rate' => 2600.00, 'description' => 'Agricultural and rice producing hub.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Laak', 'destination_rate' => 2900.00, 'description' => 'Largest municipality in area in Davao de Oro.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Mabini', 'destination_rate' => 2600.00, 'description' => 'Coastal beach and pearl farm town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Maco', 'destination_rate' => 2400.00, 'description' => 'Coastal mining and port town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Maragusan', 'destination_rate' => 3200.00, 'description' => 'Cold Spring Capital & Rafflesia sanctuary town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Mawab', 'destination_rate' => 2500.00, 'description' => 'Hot spring resort municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Monkayo', 'destination_rate' => 2800.00, 'description' => 'Gold mining hub & Mt. Diwata town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Montevista', 'destination_rate' => 2600.00, 'description' => 'Central junction municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'New Bataan', 'destination_rate' => 2900.00, 'description' => 'Mountainous eco-tourism municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao de Oro', 'city' => 'Pantukan', 'destination_rate' => 2700.00, 'description' => 'Gold mining & beach resort coast town.'],

            // Davao del Norte
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Tagum City', 'destination_rate' => 2200.00, 'description' => 'Provincial capital & Palm City of the Philippines.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Panabo City', 'destination_rate' => 2000.00, 'description' => 'Banana Capital of the Philippines.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Island Garden City of Samal', 'destination_rate' => 2800.00, 'description' => 'Premier island resort destination.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Asuncion', 'destination_rate' => 2400.00, 'description' => 'Agricultural interior municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Braulio E. Dujali', 'destination_rate' => 2200.00, 'description' => 'Rice granary town in Davao del Norte.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Carmen', 'destination_rate' => 2100.00, 'description' => 'Coastal town on Davao Gulf.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Kapalong', 'destination_rate' => 2500.00, 'description' => 'Caving capital of Davao del Norte.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'New Corella', 'destination_rate' => 2400.00, 'description' => 'Waterfalls and inland spring town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'San Isidro', 'destination_rate' => 2400.00, 'description' => 'Agricultural municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Santo Tomas', 'destination_rate' => 2300.00, 'description' => 'Banana plantation hub.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Norte', 'city' => 'Talaingod', 'destination_rate' => 2700.00, 'description' => 'Highland ancestral domain area.'],

            // Davao del Sur
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Davao City', 'destination_rate' => 1800.00, 'description' => 'Highly Urbanized City, Metropolitan hub of Mindanao.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Digos City', 'destination_rate' => 2400.00, 'description' => 'Provincial capital & Mango Capital of the South.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Bansalan', 'destination_rate' => 2600.00, 'description' => 'Gateway to Mt. Apo climbs.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Hagonoy', 'destination_rate' => 2500.00, 'description' => 'Agricultural municipality on Davao Gulf.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Kiblawan', 'destination_rate' => 2800.00, 'description' => 'Upland mining & farming town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Magsaysay', 'destination_rate' => 2700.00, 'description' => 'Rice producing upland town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Malalag', 'destination_rate' => 2700.00, 'description' => 'Port municipality on Malalag Bay.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Matanao', 'destination_rate' => 2600.00, 'description' => 'Cave and agricultural municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Padada', 'destination_rate' => 2600.00, 'description' => 'Commercial center of southern Davao del Sur.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Santa Cruz', 'destination_rate' => 2200.00, 'description' => 'Industrial & Mt. Apo eco-tourism town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao del Sur', 'city' => 'Sulop', 'destination_rate' => 2700.00, 'description' => 'Agricultural interior municipality.'],

            // Davao Occidental
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Occidental', 'city' => 'Malita', 'destination_rate' => 3200.00, 'description' => 'Provincial capital of Davao Occidental.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Occidental', 'city' => 'Don Marcelino', 'destination_rate' => 3600.00, 'description' => 'Coastal town known for surfing & fishing.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Occidental', 'city' => 'Jose Abad Santos', 'destination_rate' => 4500.00, 'description' => 'Southernmost mainland municipality of Davao region.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Occidental', 'city' => 'Santa Maria', 'destination_rate' => 3400.00, 'description' => 'Agricultural coastal town.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Occidental', 'city' => 'Sarangani', 'destination_rate' => 5000.00, 'description' => 'Island group municipality (Balut & Sarangani Islands).'],

            // Davao Oriental
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Mati City', 'destination_rate' => 3200.00, 'description' => 'Provincial capital, Dahican Beach & Sleeping Dinosaur.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Baganga', 'destination_rate' => 4000.00, 'description' => 'Carolina Lake & eastern sunrise coast.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Banaybanay', 'destination_rate' => 2900.00, 'description' => 'Rice granary of Davao Oriental.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Boston', 'destination_rate' => 4300.00, 'description' => 'Northernmost coastal town of Davao Oriental.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Caraga', 'destination_rate' => 3800.00, 'description' => 'Oldest town in Mindanao with historic church.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Cateel', 'destination_rate' => 4200.00, 'description' => 'Home of Aliwagwag Falls.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Governor Generoso', 'destination_rate' => 3500.00, 'description' => 'Cape San Agustin lighthouse & beaches.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Lupon', 'destination_rate' => 3000.00, 'description' => 'Davao Gulf coastal agricultural hub.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Manay', 'destination_rate' => 3600.00, 'description' => 'Pacific coastal municipality.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'San Isidro', 'destination_rate' => 3300.00, 'description' => 'Mt. Hamiguitan World Heritage Site gateway.'],
            ['region' => 'Region XI (Davao)', 'province' => 'Davao Oriental', 'city' => 'Tarragona', 'destination_rate' => 3400.00, 'description' => 'Coastal municipality.'],

            // ==========================================
            // REGION XII - SOCCSKSARGEN
            // ==========================================
            // Cotabato (North Cotabato)
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Kidapawan City', 'destination_rate' => 2800.00, 'description' => 'Provincial capital & City at the foot of Mt. Apo.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Alamada', 'destination_rate' => 3200.00, 'description' => 'Home of Asik-Asik Falls.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Aleosan', 'destination_rate' => 3000.00, 'description' => 'Agricultural interior town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Antipas', 'destination_rate' => 3000.00, 'description' => 'Upland rubber and fruit town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Arakan', 'destination_rate' => 3200.00, 'description' => 'Matigsalug indigenous domain area.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Banisilan', 'destination_rate' => 3300.00, 'description' => 'Highland agricultural town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Carmen', 'destination_rate' => 3100.00, 'description' => 'Major highway transport hub.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Kabacan', 'destination_rate' => 3000.00, 'description' => 'USM University town & Rice Granary.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Libungan', 'destination_rate' => 3000.00, 'description' => 'Agricultural municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Magpet', 'destination_rate' => 2900.00, 'description' => 'Mt. Apo climbing entry town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Makilala', 'destination_rate' => 2800.00, 'description' => 'Rubber production capital of Cotabato.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Matalam', 'destination_rate' => 3000.00, 'description' => 'Agricultural central town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Midsayap', 'destination_rate' => 2900.00, 'description' => 'Major commercial center of Cotabato province.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'M\'lang', 'destination_rate' => 2900.00, 'description' => 'Rice and swine producing hub.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Pigcawayan', 'destination_rate' => 3000.00, 'description' => 'Border town near Cotabato City.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Pikit', 'destination_rate' => 3100.00, 'description' => 'Historical trade municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'President Roxas', 'destination_rate' => 3000.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Cotabato', 'city' => 'Tulunan', 'destination_rate' => 3000.00, 'description' => 'Southern agricultural municipality.'],

            // Sarangani
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Alabel', 'destination_rate' => 2600.00, 'description' => 'Provincial capital of Sarangani.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Glan', 'destination_rate' => 3000.00, 'description' => 'Gumasa white sand beaches & Sarangani Bay.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Kiamba', 'destination_rate' => 3500.00, 'description' => 'Tuka Marine Park town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Maasim', 'destination_rate' => 3200.00, 'description' => 'Paragliding capital of the Philippines.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Maitum', 'destination_rate' => 3800.00, 'description' => 'Anthropomorphic burial jars heritage site.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Malapatan', 'destination_rate' => 2800.00, 'description' => 'Inabal weaving coastal town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sarangani', 'city' => 'Malungon', 'destination_rate' => 2700.00, 'description' => 'Gateway town connecting GenSan and Davao.'],

            // South Cotabato
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'General Santos City', 'destination_rate' => 2500.00, 'description' => 'Highly Urbanized City, Tuna Capital of the Philippines.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Koronadal City', 'destination_rate' => 2800.00, 'description' => 'Provincial capital & Regional center of SOCCSKSARGEN.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Banga', 'destination_rate' => 2900.00, 'description' => 'Corn granary of South Cotabato.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Lake Sebu', 'destination_rate' => 3500.00, 'description' => '7 Falls zipline & Tboli cultural lake destination.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Norala', 'destination_rate' => 3000.00, 'description' => 'Agricultural rice producing town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Polomolok', 'destination_rate' => 2600.00, 'description' => 'Dole pineapple plantation town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Santo Niño', 'destination_rate' => 3100.00, 'description' => 'Agricultural town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Surallah', 'destination_rate' => 3100.00, 'description' => 'Commercial hub of upper valley.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'T\'Boli', 'destination_rate' => 3400.00, 'description' => 'Lake Holon eco-adventure destination.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Tampakan', 'destination_rate' => 2900.00, 'description' => 'Copper and gold deposit area.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Tantangan', 'destination_rate' => 2900.00, 'description' => 'Pottery and farming municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'South Cotabato', 'city' => 'Tupi', 'destination_rate' => 2700.00, 'description' => 'Fruit basket of South Cotabato at Mt. Matutum.'],

            // Sultan Kudarat
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Tacurong City', 'destination_rate' => 3000.00, 'description' => 'Commercial city & Baras Bird Sanctuary.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Isulan', 'destination_rate' => 3100.00, 'description' => 'Provincial capital of Sultan Kudarat.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Bagumbayan', 'destination_rate' => 3300.00, 'description' => 'Coffee producing mountain town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Columbio', 'destination_rate' => 3500.00, 'description' => 'Border municipality near Davao del Sur.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Esperanza', 'destination_rate' => 3200.00, 'description' => 'Hot springs resort municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Kalamansig', 'destination_rate' => 4100.00, 'description' => 'Coastal fishing & beach municipality.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Lambayong', 'destination_rate' => 3200.00, 'description' => 'Rice granary town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Lebak', 'destination_rate' => 4000.00, 'description' => 'Major coastal city hub on Celebes Sea.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Lutayan', 'destination_rate' => 3200.00, 'description' => 'Lakeside municipality on Lake Buluan.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Palimbang', 'destination_rate' => 4200.00, 'description' => 'Southernmost coastal town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'President Quirino', 'destination_rate' => 3100.00, 'description' => 'Agricultural interior town.'],
            ['region' => 'Region XII (SOCCSKSARGEN)', 'province' => 'Sultan Kudarat', 'city' => 'Senator Ninoy Aquino', 'destination_rate' => 3600.00, 'description' => 'Cave and highland town.'],

            // ==========================================
            // REGION XIII - CARAGA REGION
            // ==========================================
            // Agusan del Norte
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Butuan City', 'destination_rate' => 0.00, 'description' => 'Highly Urbanized City, Regional Center & Balangay Heritage Hub.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Cabadbaran City', 'destination_rate' => 500.00, 'description' => 'Provincial capital of Agusan del Norte.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Buenavista', 'destination_rate' => 400.00, 'description' => 'Neighboring western municipality of Butuan.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Carmen', 'destination_rate' => 600.00, 'description' => 'Coastal town famous for mangoes & eco-resorts.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Jabonga', 'destination_rate' => 800.00, 'description' => 'Lake Mainit coastal destination.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Kitcharao', 'destination_rate' => 1000.00, 'description' => 'Northern border town near Surigao del Norte.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Las Nieves', 'destination_rate' => 600.00, 'description' => 'Agusan River valley agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Magallanes', 'destination_rate' => 600.00, 'description' => 'Historical wood processing town at Agusan River mouth.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Nasipit', 'destination_rate' => 500.00, 'description' => 'Major seaport town of Agusan del Norte.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Remedios T. Romualdez', 'destination_rate' => 500.00, 'description' => 'Rice granary municipality of Agusan del Norte.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Santiago', 'destination_rate' => 700.00, 'description' => 'Mining and agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Norte', 'city' => 'Tubay', 'destination_rate' => 600.00, 'description' => 'Coastal mining and eco-tourism town.'],

            // Agusan del Sur
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Bayugan City', 'destination_rate' => 1200.00, 'description' => 'Cut-flower capital of Caraga.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Bunawan', 'destination_rate' => 2200.00, 'description' => 'Agusan Marsh sanctuary area (Home of Lolong).'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Esperanza', 'destination_rate' => 1400.00, 'description' => 'Golden Tara heritage town along Agusan River.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'La Paz', 'destination_rate' => 1800.00, 'description' => 'Marshland agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Loreto', 'destination_rate' => 2500.00, 'description' => 'Western timberland municipality bordering Bukidnon.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Prosperidad', 'destination_rate' => 1400.00, 'description' => 'Provincial capital of Agusan del Sur.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Rosario', 'destination_rate' => 1800.00, 'description' => 'Mining and agricultural hub.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'San Francisco', 'destination_rate' => 1500.00, 'description' => 'Primary commercial hub of Agusan del Sur.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'San Luis', 'destination_rate' => 1600.00, 'description' => 'Agricultural and forestry municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Santa Josefa', 'destination_rate' => 2100.00, 'description' => 'Southern agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Sibagat', 'destination_rate' => 1000.00, 'description' => 'Gateway municipality bordering Butuan.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Talacogon', 'destination_rate' => 1600.00, 'description' => 'Historic riverside municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Trento', 'destination_rate' => 2000.00, 'description' => 'Southern gateway to Davao region.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Agusan del Sur', 'city' => 'Veruela', 'destination_rate' => 2200.00, 'description' => 'Riverine marshland municipality.'],

            // Dinagat Islands
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'San Jose', 'destination_rate' => 4000.00, 'description' => 'Provincial capital town of Dinagat Islands.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Basilisa', 'destination_rate' => 4200.00, 'description' => 'Lake Bababu & beach destinations.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Cagdianao', 'destination_rate' => 4500.00, 'description' => 'Mining & island destination.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Dinagat', 'destination_rate' => 4100.00, 'description' => 'Oldest municipality on Dinagat Island.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Libjo', 'destination_rate' => 4400.00, 'description' => 'Bonsai forest & Pangabangan Cove.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Loreto', 'destination_rate' => 4600.00, 'description' => 'Northernmost town & Mt. Redondo Pygmy Forest.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Dinagat Islands', 'city' => 'Tubajon', 'destination_rate' => 4500.00, 'description' => 'Northern coastal eco-destination.'],

            // Surigao del Norte
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Surigao City', 'destination_rate' => 2500.00, 'description' => 'Provincial capital & City of Island Adventures.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Alegria', 'destination_rate' => 2300.00, 'description' => 'Inland agricultural town near Lake Mainit.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Bacuag', 'destination_rate' => 2600.00, 'description' => 'Coastal municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Burgos', 'destination_rate' => 4800.00, 'description' => 'Northern Siargao surfing spot.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Claver', 'destination_rate' => 2800.00, 'description' => 'Bucas Grande entry point & mineral mining hub.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Dapa', 'destination_rate' => 4500.00, 'description' => 'Main entry port town of Siargao Island.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Del Carmen', 'destination_rate' => 4500.00, 'description' => 'Sugba Lagoon & Mangrove sanctuary on Siargao.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'General Luna', 'destination_rate' => 4500.00, 'description' => 'Cloud 9 Surfing Capital of the Philippines.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Gigaquit', 'destination_rate' => 2700.00, 'description' => 'Home of Gigaquit Wine (Baal).'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Mainit', 'destination_rate' => 2200.00, 'description' => 'Lake Mainit hot springs area.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Malimono', 'destination_rate' => 2600.00, 'description' => 'Western coastal town facing Sea.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Pilar', 'destination_rate' => 4700.00, 'description' => 'Magpupungko Rock Pools on Siargao.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Placer', 'destination_rate' => 2600.00, 'description' => 'Historic gold mining coastal town.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'San Benito', 'destination_rate' => 4600.00, 'description' => 'Western Siargao mangrove island town.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'San Francisco', 'destination_rate' => 2700.00, 'description' => 'Anao-aon Island municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'San Isidro', 'destination_rate' => 4700.00, 'description' => 'Pacific ocean coastal town on Siargao.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Santa Monica', 'destination_rate' => 4800.00, 'description' => 'Northern tip of Siargao Island (Danjug Cave).'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Sison', 'destination_rate' => 2400.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Socorro', 'destination_rate' => 4200.00, 'description' => 'Bucas Grande Island & Sohoton Cove sanctuary.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Tagana-an', 'destination_rate' => 2600.00, 'description' => 'Coastal island-studded municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Norte', 'city' => 'Tubod', 'destination_rate' => 2400.00, 'description' => 'Inland agricultural town.'],

            // Surigao del Sur
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Tandag City', 'destination_rate' => 2800.00, 'description' => 'Provincial capital of Surigao del Sur.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Bislig City', 'destination_rate' => 3200.00, 'description' => 'Home of Tinuy-an Falls & Baywalk.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Barobo', 'destination_rate' => 3100.00, 'description' => 'Highway crossroads town with Bogac Cold Spring.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Bayabas', 'destination_rate' => 2900.00, 'description' => 'Coastal eco-tourism municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Cagwait', 'destination_rate' => 3000.00, 'description' => 'Cagwait White Beach (Waikiki of the Philippines).'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Cantilan', 'destination_rate' => 2600.00, 'description' => 'Cradle of Caraga culture & Huyamao Island.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Carmen', 'destination_rate' => 2600.00, 'description' => 'Coastal municipality in northern Surigao del Sur.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Carrascal', 'destination_rate' => 2500.00, 'description' => 'Northernmost mining & eco-tourism town.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Cortes', 'destination_rate' => 2700.00, 'description' => 'Laswitan Lagoon & ocean splash destination.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Hinatuan', 'destination_rate' => 3500.00, 'description' => 'World-famous Hinatuan Enchanted River.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Lanuza', 'destination_rate' => 2600.00, 'description' => 'Surfing destination of Surigao del Sur.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Lianga', 'destination_rate' => 2900.00, 'description' => 'Bao-bao Falls & coastal beach resorts.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Lingig', 'destination_rate' => 3400.00, 'description' => 'Southernmost town bordering Davao Oriental.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Madrid', 'destination_rate' => 2600.00, 'description' => 'Agricultural coastal town.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Marihatag', 'destination_rate' => 2800.00, 'description' => 'Coastal town with pristine beaches.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'San Agustin', 'destination_rate' => 3000.00, 'description' => 'Gateway to Britania Group of 24 Islands.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'San Miguel', 'destination_rate' => 2900.00, 'description' => 'Largest inland agricultural municipality.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Tagbina', 'destination_rate' => 3200.00, 'description' => 'Agricultural interior town.'],
            ['region' => 'Region XIII (Caraga)', 'province' => 'Surigao del Sur', 'city' => 'Tago', 'destination_rate' => 2800.00, 'description' => 'Agricultural town neighboring Tandag.'],

            // ==========================================
            // BARMM - BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO
            // ==========================================
            // Basilan
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Isabela City', 'destination_rate' => 4500.00, 'description' => 'Malamawi White Beach & capital city.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Lamitan City', 'destination_rate' => 4800.00, 'description' => 'Cultural center & capital city of Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Akbar', 'destination_rate' => 4900.00, 'description' => 'Coastal municipality in Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Al-Barka', 'destination_rate' => 5000.00, 'description' => 'Southern municipality in Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Hadji Mohammad Ajul', 'destination_rate' => 4900.00, 'description' => 'Eastern coastal municipality.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Hadji Muhtamad', 'destination_rate' => 5200.00, 'description' => 'Tapiantana island group municipality.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Lantawan', 'destination_rate' => 4800.00, 'description' => 'Western coastal municipality.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Maluso', 'destination_rate' => 4700.00, 'description' => 'Major port municipality of Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Sumisip', 'destination_rate' => 5000.00, 'description' => 'Largest municipality by land area in Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Tabuan-Lasa', 'destination_rate' => 5200.00, 'description' => 'Island group municipality.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Tipo-Tipo', 'destination_rate' => 4900.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Tuburan', 'destination_rate' => 4800.00, 'description' => 'Eastern municipality in Basilan.'],
            ['region' => 'BARMM', 'province' => 'Basilan', 'city' => 'Ungkaya Pukan', 'destination_rate' => 4900.00, 'description' => 'Inland municipality in Basilan.'],

            // Lanao del Sur
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Marawi City', 'destination_rate' => 3500.00, 'description' => 'Islamic City of the Philippines & Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Amai Manabilang', 'destination_rate' => 3200.00, 'description' => 'Highland agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Bacolod-Kalawi', 'destination_rate' => 3600.00, 'description' => 'Lakeside municipality on Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Balabagan', 'destination_rate' => 3800.00, 'description' => 'Coastal municipality on Illana Bay.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Balindong', 'destination_rate' => 3500.00, 'description' => 'Lakeside town on Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Bayang', 'destination_rate' => 3700.00, 'description' => 'Historic lakeside town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Binidayan', 'destination_rate' => 3700.00, 'description' => 'Lakeside municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Buadiposo-Buntong', 'destination_rate' => 3600.00, 'description' => 'Lakeside town east of Marawi.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Bubong', 'destination_rate' => 3600.00, 'description' => 'Agricultural interior municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Butig', 'destination_rate' => 3800.00, 'description' => 'Historical mountain municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Calanogas', 'destination_rate' => 3600.00, 'description' => 'Inland municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Ditsaan-Ramain', 'destination_rate' => 3500.00, 'description' => 'Agricultural town east of Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Ganassi', 'destination_rate' => 3700.00, 'description' => 'Southwestern lake shore town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Kapai', 'destination_rate' => 3600.00, 'description' => 'Highland interior municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Katai', 'destination_rate' => 3700.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Lumba-Bayabao', 'destination_rate' => 3600.00, 'description' => 'Largest municipality in Lanao del Sur.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Lumbaca-Unayan', 'destination_rate' => 3700.00, 'description' => 'Lakeside municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Lumbatan', 'destination_rate' => 3700.00, 'description' => 'Lakeside agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Lumbayanague', 'destination_rate' => 3700.00, 'description' => 'Eastern shore Lake Lanao town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Madalum', 'destination_rate' => 3600.00, 'description' => 'Western shore Lake Lanao municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Madamba', 'destination_rate' => 3700.00, 'description' => 'Interior agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Maguing', 'destination_rate' => 3500.00, 'description' => 'Forest and agricultural interior town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Malabang', 'destination_rate' => 3700.00, 'description' => 'Historic coastal port town on Illana Bay.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Marantao', 'destination_rate' => 3400.00, 'description' => 'Woodcarving and brassware town near Marawi.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Marogong', 'destination_rate' => 3800.00, 'description' => 'Highland interior municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Masiu', 'destination_rate' => 3600.00, 'description' => 'Historic royal principality on Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Mulondo', 'destination_rate' => 3600.00, 'description' => 'Eastern shore Lake Lanao town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Pagayawan', 'destination_rate' => 3700.00, 'description' => 'Interior agricultural town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Piagapo', 'destination_rate' => 3500.00, 'description' => 'Mountainous interior town near Iligan border.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Picong', 'destination_rate' => 3800.00, 'description' => 'Coastal town on Illana Bay.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Poona Bayabao', 'destination_rate' => 3600.00, 'description' => 'Eastern lake basin municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Pualas', 'destination_rate' => 3700.00, 'description' => 'Southwestern lake municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Saguiaran', 'destination_rate' => 3400.00, 'description' => 'Gateway town immediately adjacent to Marawi.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Sultan Dumalondong', 'destination_rate' => 3600.00, 'description' => 'Inland agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Tagoloan II', 'destination_rate' => 3500.00, 'description' => 'Eastern highland border town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Tamparan', 'destination_rate' => 3600.00, 'description' => 'Major healthcare and trade hub on Lake Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Taraka', 'destination_rate' => 3600.00, 'description' => 'Historic town with oldest mosque site in Lanao.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Tubaran', 'destination_rate' => 3800.00, 'description' => 'Southern inland mountain town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Tugaya', 'destination_rate' => 3600.00, 'description' => 'UNESCO-recognized cottage industry brassware town.'],
            ['region' => 'BARMM', 'province' => 'Lanao del Sur', 'city' => 'Wao', 'destination_rate' => 3000.00, 'description' => 'Highland agricultural basin town bordering Bukidnon.'],

            // Maguindanao del Norte
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Cotabato City', 'destination_rate' => 3000.00, 'description' => 'Independent Component City & BARMM Regional Center.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Barira', 'destination_rate' => 3500.00, 'description' => 'Northern mountain municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Buldon', 'destination_rate' => 3500.00, 'description' => 'Highland forestry municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Datu Blah T. Sinsuat', 'destination_rate' => 3600.00, 'description' => 'Coastal fishing municipality along Moro Gulf.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Datu Odin Sinsuat', 'destination_rate' => 3200.00, 'description' => 'Provincial capital, Pink Mosque & Awang Airport.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Kabuntalan', 'destination_rate' => 3300.00, 'description' => 'Riverine marshland municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Matanog', 'destination_rate' => 3400.00, 'description' => 'Border town near Lanao del Sur.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Northern Kabuntalan', 'destination_rate' => 3300.00, 'description' => 'Delta riverine municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Parang', 'destination_rate' => 3300.00, 'description' => 'Polloc Free Port & coastal town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Sultan Kudarat', 'destination_rate' => 3100.00, 'description' => 'Suburban town hosting Grand Mosque of Cotabato.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Sultan Mastura', 'destination_rate' => 3300.00, 'description' => 'Coastal and agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Talitay', 'destination_rate' => 3400.00, 'description' => 'Agricultural interior municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Norte', 'city' => 'Upi', 'destination_rate' => 3400.00, 'description' => 'Highland Teduray ancestral cultural town.'],

            // Maguindanao del Sur
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Buluan', 'destination_rate' => 3500.00, 'description' => 'Provincial capital town on Lake Buluan.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Ampatuan', 'destination_rate' => 3400.00, 'description' => 'Agricultural interior town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Anggal Midtimbang', 'destination_rate' => 3400.00, 'description' => 'Central agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Hoffer Ampatuan', 'destination_rate' => 3500.00, 'description' => 'Highland agricultural town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Montawal', 'destination_rate' => 3300.00, 'description' => 'Border town near Kabacan, Cotabato.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Paglas', 'destination_rate' => 3400.00, 'description' => 'Banana plantation agricultural town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Piang', 'destination_rate' => 3400.00, 'description' => 'Historic inland trade town on Pulangi river.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Salibo', 'destination_rate' => 3500.00, 'description' => 'Ligawasan Marshland municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Datu Unsay', 'destination_rate' => 3500.00, 'description' => 'Agricultural inland municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'General Salipada K. Pendatun', 'destination_rate' => 3500.00, 'description' => 'Lakeside corn and rice town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Guindulungan', 'destination_rate' => 3400.00, 'description' => 'Highway junction municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Mamasapano', 'destination_rate' => 3500.00, 'description' => 'Ligawasan marsh agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Mangudadatu', 'destination_rate' => 3500.00, 'description' => 'Lakeside municipality on Lake Buluan.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Pagalungan', 'destination_rate' => 3300.00, 'description' => 'Pulangi riverine agricultural hub.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Paglat', 'destination_rate' => 3400.00, 'description' => 'Agricultural inland town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Pandag', 'destination_rate' => 3500.00, 'description' => 'Lakeside farming municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Rajah Buayan', 'destination_rate' => 3500.00, 'description' => 'Marshland agricultural municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Shariff Aguak', 'destination_rate' => 3400.00, 'description' => 'Historical capital municipality.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Shariff Saydona Mustapha', 'destination_rate' => 3500.00, 'description' => 'Marshland interior town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'South Upi', 'destination_rate' => 3600.00, 'description' => 'Highland indigenous ancestral domain.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Sultan sa Barongis', 'destination_rate' => 3500.00, 'description' => 'Agricultural river town.'],
            ['region' => 'BARMM', 'province' => 'Maguindanao del Sur', 'city' => 'Talayan', 'destination_rate' => 3400.00, 'description' => 'Inland agricultural municipality.'],

            // Sulu
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Jolo', 'destination_rate' => 5000.00, 'description' => 'Provincial capital town of Sulu Archipelago.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Banguingui', 'destination_rate' => 5500.00, 'description' => 'Tongkil island group municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Hadji Panglima Tahil', 'destination_rate' => 5200.00, 'description' => 'Marunggas island municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Indanan', 'destination_rate' => 5100.00, 'description' => 'Agricultural municipality adjacent to Jolo.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Kalingalan Caluang', 'destination_rate' => 5300.00, 'description' => 'Eastern coastal municipality on Luuk.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Lugus', 'destination_rate' => 5400.00, 'description' => 'Tapul island group municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Luuk', 'destination_rate' => 5300.00, 'description' => 'Eastern island municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Maimbung', 'destination_rate' => 5200.00, 'description' => 'Historical royal seat of Sultanate of Sulu.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Old Panamao', 'destination_rate' => 5300.00, 'description' => 'Lakeside municipality on Lake Panamao.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Omar', 'destination_rate' => 5300.00, 'description' => 'Coastal municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Pandami', 'destination_rate' => 5400.00, 'description' => 'Laparan island municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Panglima Estino', 'destination_rate' => 5200.00, 'description' => 'Inland municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Pangutaran', 'destination_rate' => 5600.00, 'description' => 'Outlying island municipality northwest of Jolo.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Parang', 'destination_rate' => 5200.00, 'description' => 'Western coastal town with pristine white beaches.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Pata', 'destination_rate' => 5400.00, 'description' => 'Pata Island municipality.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Patikul', 'destination_rate' => 5100.00, 'description' => 'Fruit growing coastal municipality near Jolo.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Siasi', 'destination_rate' => 5500.00, 'description' => 'Major commercial island hub of southern Sulu.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Talipao', 'destination_rate' => 5200.00, 'description' => 'Largest inland mountain municipality in Sulu.'],
            ['region' => 'BARMM', 'province' => 'Sulu', 'city' => 'Tapul', 'destination_rate' => 5400.00, 'description' => 'Tapul Island municipality.'],

            // Tawi-Tawi
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Bongao', 'destination_rate' => 5500.00, 'description' => 'Provincial capital town & sacred Bud Bongao peak.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Languyan', 'destination_rate' => 5800.00, 'description' => 'Timberland & coastal island municipality.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Mapun', 'destination_rate' => 6500.00, 'description' => 'Isolated island municipality in Sulu Sea.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Panglima Sugala', 'destination_rate' => 5700.00, 'description' => 'Old capital town & sea gypsy anchorage.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Sapa-Sapa', 'destination_rate' => 5800.00, 'description' => 'Stilt village island municipality.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Sibutu', 'destination_rate' => 6000.00, 'description' => 'Southernmost island municipality in the Philippines.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Simunul', 'destination_rate' => 5800.00, 'description' => 'Site of Sheikh Makhdum Mosque (1st in PH).'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Sitangkai', 'destination_rate' => 6200.00, 'description' => 'Venice of the Philippines stilt town.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'South Ubian', 'destination_rate' => 6000.00, 'description' => 'Outlying island group municipality.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Tandubas', 'destination_rate' => 5900.00, 'description' => 'Seaweed farming island municipality.'],
            ['region' => 'BARMM', 'province' => 'Tawi-Tawi', 'city' => 'Turtle Islands', 'destination_rate' => 7000.00, 'description' => 'Protected Green Sea Turtle sanctuary island reserve.'],
        ];

        foreach ($destinations as $dest) {
            Destination::updateOrCreate(
                [
                    'region' => $dest['region'],
                    'province' => $dest['province'],
                    'city' => $dest['city'],
                ],
                [
                    'destination_rate' => $dest['destination_rate'],
                    'description' => $dest['description'],
                ]
            );
        }
    }
}
